// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qulglzsnilsqfhbtpjmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1bGdsenNuaWxzcWZoYnRwam1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NTA2ODUsImV4cCI6MjA2OTUyNjY4NX0.J8jHjHtITT-AnBHKeKs6X3HNpvhBkXp3EeIsw9Oe2CU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});